"""SQLAlchemy models, one module per Postgres schema (content, core, game,
social, mod, srs). Schemas are module boundaries — see CLAUDE.md."""
from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Consistent naming conventions make autogenerated migrations stable.
metadata = MetaData(
    naming_convention={
        "ix": "ix_%(column_0_label)s",
        "uq": "uq_%(table_name)s_%(column_0_name)s",
        "ck": "ck_%(table_name)s_%(constraint_name)s",
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
        "pk": "pk_%(table_name)s",
    }
)


class Base(DeclarativeBase):
    metadata = metadata
